<?php
declare(strict_types=1);
namespace Nebule\Application\Modules;
use Nebule\Library\nebule;
use Nebule\Library\References;
use Nebule\Library\Metrology;
use Nebule\Library\Applications;
use Nebule\Library\Displays;
use Nebule\Library\Actions;
use Nebule\Library\Translates;
use Nebule\Library\ModuleInterface;
use Nebule\Library\Modules;
use Nebule\Library\ModelModuleHelp;
use Nebule\Library\ModuleTranslates;

/**
 * This module adds translation in Ukrainian UA-UA.
 *
 * @author Projet nebule
 * @license GNU GPLv3
 * @copyright Projet nebule
 * @link www.nebule.org
 */
class ModuleTranslateUAUA extends ModuleTranslates
{
    const MODULE_LANGUAGE = 'ua-ua';
    const MODULE_NAME = '::translateModule:ua-ua:ModuleName';
    const MODULE_MENU_NAME = '::translateModule:ua-ua:MenuName';
    const MODULE_DESCRIPTION = '::translateModule:ua-ua:ModuleDescription';
    const MODULE_VERSION = '020260101';
    const MODULE_AUTHOR = 'Projet nebule';
    const MODULE_LICENCE = 'GNU GLP v3 2013-2026';
    const MODULE_LOGO = 'ca405d670fb5a386e43a71169cd4d10288032c081912f7e83e140d3244d3b222.sha2.256';
    const MODULE_INTERFACE = '3.0';
    CONST TRANSLATE_TABLE = [
        'en-en' => [
            '::translateModule:ua-ua:ModuleName' => 'Ukrainian (Ukraine)',
            '::translateModule:ua-ua:MenuName' => 'Ukrainian (Ukraine)',
            '::translateModule:ua-ua:ModuleDescription' => 'Interface translation in Ukrainian.',
            '::translateModule:ua-ua:ModuleHelp' => 'This module permit to translate the nebule applications in Ukrainian.',
        ],
        'ua-ua' => [
            '::translateModule:ua-ua:ModuleName' => 'Українська (Україна)',
            '::translateModule:ua-ua:MenuName' => 'Українська (Україна)',
            '::translateModule:ua-ua:ModuleDescription' => 'Переклад інтерфейсу українською мовою.',
            '::translateModule:ua-ua:ModuleHelp' => 'Цей модуль дозволяє перекладати додатки nebule українською мовою.',

            'nebule/objet' => 'Object',
            'nebule/objet/hash' => 'Hash type',
            'nebule/objet/type' => 'MIME type',
            'nebule/objet/taille' => 'Size',
            'nebule/objet/nom' => 'Name',
            'nebule/objet/prefix' => 'Prefix',
            'nebule/objet/prenom' => 'First name',
            'nebule/objet/suffix' => 'Suffix',
            'nebule/objet/surnom' => 'Nickname',
            'nebule/objet/postnom' => 'Nickname',
            'nebule/objet/entite' => 'Entity',
            'nebule/objet/entite/type' => 'Type',
            'nebule/objet/date' => 'Date',
            'nebule/objet/date/annee' => 'Year',
            'nebule/objet/date/mois' => 'Month',
            'nebule/objet/date/jour' => 'Day',
            'nebule/objet/date/heure' => 'Hour',
            'nebule/objet/date/minute' => 'Minute',
            'nebule/objet/date/seconde' => 'Second',
            'nebule/objet/date/zone' => 'Zone de temps',
            'nebule/objet/emotion/colere' => 'Annoying',
            'nebule/objet/emotion/degout' => 'Bummed',
            'nebule/objet/emotion/surprise' => 'Surprised',
            'nebule/objet/emotion/peur' => 'disturbed',
            'nebule/objet/emotion/interet' => 'Interested',
            'nebule/objet/emotion/joie' => 'I like',
            'nebule/objet/emotion/confiance' => 'Agree',
            'nebule/objet/emotion/tristesse' => 'Sadly',
            'nebule/objet/entite/localisation' => 'Localisation',
            'nebule/objet/entite/maitre/securite' => 'Master of security',
            'nebule/objet/entite/maitre/code' => 'Master of code',
            'nebule/objet/entite/maitre/annuaire' => 'Master of directory',
            'nebule/objet/entite/maitre/temps' => 'Master of time',
            References::REFERENCE_OBJECT_TEXT => 'RAW text',
            'application/x-pem-file' => 'Entity',
            'image/jpeg' => 'JPEG picture',
            'image/png' => 'PNG picture',
            'application/x-bzip2' => 'Archive BZIP2',
            'text/html' => 'HTML page',
            'application/x-php' => 'PHP code',
            'application/x-httpd-php' => 'PHP code',
            'text/x-php' => 'PHP code',
            'text/css' => 'Cascading Style Sheet CSS',
            'audio/mpeg' => 'Audio MP3',
            'audio/x-vorbis+ogg' => 'Audio OGG',
            'application/x-encrypted/rsa' => 'Encrypted',
            'application/x-encrypted/aes-256-ctr' => 'Encrypted',
            'application/x-folder' => 'Folder',
            '::Welcome' => 'Welcome',
            '::INFO' => 'Information',
            '::OK' => 'OK',
            '::INFORMATION' => 'Message',
            '::WARN' => 'WARNING!',
            '::ERROR' => 'ERROR!',
            '::RESCUE' => 'Rescue mode!',
            '::GO' => 'Continue',
            '::BACK' => 'Go back',
            '::SecurityChecks' => 'Security checks',
            '::icon:DEFAULT_ICON_LO' => 'Object',
            '::HtmlHeadDescription' => 'Client web page sylabe for nebule.',
            '::Experimental' => '[Experimental]',
            '::Developpement' => '[Under developpement]',
            '::help' => 'Help',
            '::IDprivateKey' => 'Private ID',
            '::IDpublicKey' => 'Public ID',
            '::Password' => 'Password',
            '::Switch' => 'Switching',
            '::Query' => 'Query',
            '::node' => 'node',
            '::Node' => 'Node',
            '::group' => 'group',
            '::Group' => 'Group',
            '::entity' => 'entity',
            '::Entity' => 'Entity',
            '::location' => 'location',
            '::Location' => 'Location',
            '::conversation' => 'conversation',
            '::Conversation' => 'Conversation',
            '::currency' => 'currency',
            '::Currency' => 'Currency',
            '::tokenpool' => 'token pool',
            '::Tokenpool' => 'Token pool',
            '::token' => 'token',
            '::Token' => 'Token',
            '::wallet' => 'wallet',
            '::Wallet' => 'Wallet',
            '::display:content:errorBan' => "This object is banned, it can't be displayed!",
            '::display:content:warningTaggedWarning' => "This object is marked as dangerous, be carfull with it's content!",
            '::display:content:ObjectProctected' => "This object is marked as protected!",
            '::display:content:warningObjectProctected' => "This object is marked as protected, be careful when it's content is displayed in public!",
            '::display:content:OK' => 'The object content is valid.',
            '::display:content:warningTooBig' => "This object is too big, it's content have not been checked!",
            '::display:content:errorNotDisplayable' => "This object can't be displayed!",
            '::display:content:errorNotAvailable' => "This object is not available, it can't be displayed!",
            '::display:content:notAnObject' => 'This reference object do not have content.',
            '::display:content:ObjectHaveUpdate' => 'This object have been updated to:',
            '::display:content:Activated' => 'This object is activated.',
            '::display:content:NotActivated' => 'This object is not activated.',
            '::display:link:OK' => 'This link is valid.',
            '::display:link:errorInvalid' => 'This link is invalid!',
            '::warn_ServNotPermitWrite' => 'This server do not permit modifications.',
            '::warn_flushSessionAndCache' => 'All datas of this connexion have been flushed.',
            '::err_NotPermit' => 'Non autorisé sur ce serveur !',
            '::act_chk_errCryptHash' => "La fonction de prise d'empreinte cryptographique ne fonctionne pas correctement !",
            '::act_chk_warnCryptHashkey' => "La taille de l'empreinte cryptographique est trop petite !",
            '::act_chk_errCryptHashkey' => "La taille de l'empreinte cryptographique est invalide !",
            '::act_chk_errCryptSym' => "La fonction de chiffrement cryptographique symétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est trop petite !",
            '::act_chk_errCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est invalide !",
            '::act_chk_errCryptAsym' => "La fonction de chiffrement cryptographique asymétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est trop petite !",
            '::act_chk_errCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est invalide !",
            '::act_chk_errBootstrap' => "L'empreinte cryptographique du bootstrap est invalide !",
            '::act_chk_warnSigns' => 'La vérification des signatures de liens est désactivée !',
            '::act_chk_errSigns' => 'La vérification des signatures de liens ne fonctionne pas !',
            '::info_OnlySignedLinks' => 'Only signed links!',
            '::info_OnlyLinksFromCodeMaster' => 'Only links signed by the code master!',
            '::display:object:flag:protected' => 'This object is protected.',
            '::display:object:flag:unprotected' => 'This object is not protected.',
            '::display:object:flag:obfuscated' => 'This object is obfuscated.',
            '::display:object:flag:unobfuscated' => 'This object is not obfuscated.',
            '::display:object:flag:locked' => 'This entity is locked.',
            '::display:object:flag:unlocked' => 'This entity is unlocked.',
            '::display:object:flag:activated' => 'This object is activated.',
            '::display:object:flag:unactivated' => 'This object is not activated.',
            '::list:empty' => 'Empty list',
            '::yes' => 'Yes',
            '::no' => 'No',
            '::lock' => 'Locking',
            '::unlock' => 'Unlocking',
            '::entity:locked' => 'Entity locked. Unlock?',
            '::entity:unlocked' => 'Entity unlocked. Lock?',
            '::allApplications' => 'Bootstrap and applications',
            '::Version' => 'Version',
            '::UniqueID' => 'Universal identifier : %s',
            '::GroupeFerme' => 'Closed group',
            '::GroupeOuvert' => 'Opened group',
            '::ConversationFermee' => 'Closed conversation',
            '::ConversationOuverte' => 'Opened conversation',
            '::progress' => 'In progress...',
            '::seeMore' => 'See more...',
            '::noContent' => '(content not available)',
            '::appSwitch' => 'Switch application',
            '::menu' => 'Menu',
            '::menuDesc' => 'Page with full menu',
            '::EmptyList' => 'Empty list.',
            '::ChangeLanguage' => 'Change language',
            '::SelectUser' => 'Select user',
            '::MarkAdd' => 'Mark',
            '::MarkRemove' => 'Unmark',
            '::MarkRemoveAll' => 'Unmark all',
            '::Synchronize' => 'Synchronize',
            '::notImplemented' => 'Not yet implemented...',
            '::notSupported' => 'Not supported...',
            '::password' => 'Password',
            '::login' => 'Connecting',
            '::confirm' => 'Confirm',
            '::privateKey' => 'Private key',
            '::connexion' => 'Connection',
            '::logout' => 'Disconnecting',
            '::selfLogout' => 'Disconnecting myself',
            '::flush' => 'Disconnecting all',
            '::return' => 'Return to application',
            '::err_NoPrivKey' => 'No private key!',
            '::previousPage' => 'Previous page',
            '::nextPage' => 'Next page',
            '::page%s%s%s%s%s' => 'Page %s/%s (%s-%s on %s)',
        ],
    ];
}
