<?php
declare(strict_types=1);
namespace Nebule\Application\Modules;
use Nebule\Library\nebule;
use Nebule\Library\References;
use Nebule\Library\Metrology;
use Nebule\Library\Applications;
use Nebule\Library\Displays;
use Nebule\Library\Actions;
use Nebule\Library\Translates;
use Nebule\Library\ModuleInterface;
use Nebule\Library\Module;
use Nebule\Library\ModelModuleHelp;
use Nebule\Library\ModuleTranslates;

/**
 * This module adds translation in Spanish ES-ES.
 *
 * @author Projet nebule
 * @license GNU GPLv3
 * @copyright Projet nebule
 * @link www.nebule.org
 */
class ModuleTranslateESES extends ModuleTranslates
{
    const MODULE_LANGUAGE = 'es-es';
    const MODULE_NAME = '::translateModule:es-es:ModuleName';
    const MODULE_MENU_NAME = '::translateModule:es-es:MenuName';
    const MODULE_DESCRIPTION = '::translateModule:es-es:ModuleDescription';
    const MODULE_VERSION = '020260110';
    const MODULE_AUTHOR = 'Projet nebule';
    const MODULE_LICENCE = 'GNU GLP v3 2013-2026';
    const MODULE_LOGO = '501a2e49c23fd101dd8ba361881c75e1fb5cdc061e0232148513aea162ff107b.sha2.256';
    const MODULE_INTERFACE = '3.0';
    CONST TRANSLATE_TABLE = [
        'en-en' => [
            '::translateModule:es-es:ModuleName' => 'Spanish (Spain)',
            '::translateModule:es-es:MenuName' => 'Spanish (Spain)',
            '::translateModule:es-es:ModuleDescription' => 'Interface translation in Spanish.',
            '::translateModule:es-es:ModuleHelp' => 'This module permit to translate the nebule applications in Spanish.',
        ],
        'es-es' => [
            '::translateModule:es-es:ModuleName' => 'Español (Spain)',
            '::translateModule:es-es:MenuName' => 'Español (Spain)',
            '::translateModule:es-es:ModuleDescription' => 'Interface translation in Spanish.',
            '::translateModule:es-es:ModuleHelp' => 'This module permit to translate the nebule applications in Spanish.',

            'nebule/objet' => 'Objeto',
            'nebule/objet/hash' => 'Typo huella',
            'nebule/objet/type' => 'Tipo MIME',
            'nebule/objet/Taille' => 'Tamaño',
            'nebule/objet/nom' => 'Nombre',
            'nebule/objet/prefix' => 'Prefijo',
            'nebule/objet/prenom' => 'Primer nombre',
            'nebule/objet/suffix' => 'Sufijo',
            'nebule/objet/surnom' => 'Apodo',
            'nebule/objet/postnom' => 'Apodo',
            'nebule/objet/entite' => 'Entidad',
            'nebule/objet/entite/type' => 'Tipo',
            'nebule/objet/date' => 'Dato',
            'nebule/objet/date/annee' => 'Año',
            'nebule/objet/date/mois' => 'Mes',
            'nebule/objet/date/jour' => 'Dia',
            'nebule/objet/date/heure' => 'Hora',
            'nebule/objet/date/minute' => 'Minuto',
            'nebule/objet/date/seconde' => 'Segundo',
            'nebule/objet/date/zone' => 'Zona horaria',
            'nebule/objet/emotion/colere' => 'Molesto',
            'nebule/objet/emotion/degout' => 'Disgustado',
            'nebule/objet/emotion/surprise' => 'Sorprendente',
            'nebule/objet/emotion/peur' => 'Inquietante',
            'nebule/objet/emotion/interet' => 'Interesadas',
            'nebule/objet/emotion/joie' => 'Me gusta',
            'nebule/objet/emotion/confiance' => 'Apruebo',
            'nebule/objet/emotion/tristesse' => 'Tristemente',
            'nebule/objet/entite/localisation' => 'Localisation',
            'nebule/objet/entite/maitre/securite' => 'Maestro de seguridad',
            'nebule/objet/entite/maitre/code' => 'Maestro de codigo',
            'nebule/objet/entite/maitre/annuaire' => 'Maestro de directorio',
            'nebule/objet/entite/maitre/temps' => 'Maestro de tiempo',
            References::REFERENCE_OBJECT_TEXT => 'Texto en bruto',
            'application/x-pem-file' => 'Entidad',
            'image/jpeg' => 'JPEG gráfico',
            'image/png' => 'PNG gráfico',
            'application/x-bzip2' => 'Archivo BZIP2',
            'text/html' => 'Página HTML',
            'application/x-php' => 'Código PHP',
            'application/x-httpd-php' => 'Código PHP',
            'text/x-php' => 'Código PHP',
            'text/css' => 'Hojas de estilo en cascada CSS',
            'audio/mpeg' => 'Audio MP3',
            'audio/x-vorbis+ogg' => 'Audio OGG',
            'application/x-encrypted/rsa' => 'Encriptado',
            'application/x-encrypted/aes-256-ctr' => 'Encriptado',
            'application/x-folder' => 'Archivo',
            '::Welcome' => 'Bienvenido',
            '::INFO' => 'Information',
            '::OK' => 'OK',
            '::INFORMATION' => 'Mensaje',
            '::WARN' => '¡ADVERTENCIA!',
            '::ERROR' => '¡ERROR!',
            '::RESCUE' => '¡Modo de rescate!',
            '::GO' => 'Avanzar',
            '::BACK' => 'Volver atrás',
            '::SecurityChecks' => 'Controles de seguridad',
            '::icon:DEFAULT_ICON_LO' => 'Objeto',
            '::HtmlHeadDescription' => 'Página web cliente sylabe para nebule.',
            '::Experimental' => '[Experimental]',
            '::Developpement' => '[Under developpement]',
            '::help' => 'Ayuda',
            '::IDprivateKey' => 'ID privé',
            '::IDpublicKey' => 'ID public',
            '::Password' => 'Contraseña',
            '::Switch' => 'Cambiar',
            '::Query' => 'Pregunta',
            '::node' => 'node',
            '::Node' => 'Node',
            '::entity' => 'entity',
            '::Entity' => 'Entity',
            '::location' => 'location',
            '::Location' => 'Location',
            '::currency' => 'currency',
            '::Currency' => 'Currency',
            '::tokenpool' => 'token pool',
            '::Tokenpool' => 'Token pool',
            '::token' => 'token',
            '::Token' => 'Token',
            '::wallet' => 'wallet',
            '::Wallet' => 'Wallet',
            '::display:content:errorBan' => "This object is banned, it can't be displayed!",
            '::display:content:warningTaggedWarning' => "This object is marked as dangerous, be carfull with it's content!",
            '::display:content:ObjectProctected' => "This object is marked as protected!",
            '::display:content:warningObjectProctected' => "This object is marked as protected, be careful when it's content is displayed in public!",
            '::display:content:OK' => 'The object content is valid.',
            '::display:content:warningTooBig' => "This object is too big, it's content have not been checked!",
            '::display:content:errorNotDisplayable' => "This object can't be displayed!",
            '::display:content:errorNotAvailable' => "This object is not available, it can't be displayed!",
            '::display:content:notAnObject' => 'This reference object do not have content.',
            '::display:content:ObjectHaveUpdate' => 'This object have been updated to:',
            '::display:content:Activated' => 'This object is activated.',
            '::display:content:NotActivated' => 'This object is not activated.',
            '::display:link:OK' => 'This link is valid.',
            '::display:link:errorInvalid' => 'This link is invalid!',
            '::warn_ServNotPermitWrite' => 'This server do not permit modifications.',
            '::warn_flushSessionAndCache' => 'All datas of this connexion have been flushed',
            '::err_NotPermit' => 'Non autorisé sur ce serveur !',
            '::err_NoPrivKey' => 'No private key!',
            '::act_chk_errCryptHash' => "La fonction de prise d'empreinte cryptographique ne fonctionne pas correctement !",
            '::act_chk_warnCryptHashkey' => "La taille de l'empreinte cryptographique est trop petite !",
            '::act_chk_errCryptHashkey' => "La taille de l'empreinte cryptographique est invalide !",
            '::act_chk_errCryptSym' => "La fonction de chiffrement cryptographique symétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est trop petite !",
            '::act_chk_errCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est invalide !",
            '::act_chk_errCryptAsym' => "La fonction de chiffrement cryptographique asymétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est trop petite !",
            '::act_chk_errCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est invalide !",
            '::act_chk_errBootstrap' => "L'empreinte cryptographique du bootstrap est invalide !",
            '::act_chk_warnSigns' => 'La vérification des signatures de liens est désactivée !',
            '::act_chk_errSigns' => 'La vérification des signatures de liens ne fonctionne pas !',
            '::info_OnlySignedLinks' => 'Only signed links!',
            '::info_OnlyLinksFromCodeMaster' => 'Only links signed by the code master!',
            '::display:object:flag:protected' => 'Este objeto está protegido.',
            '::display:object:flag:unprotected' => 'Este objeto no está protegido.',
            '::display:object:flag:obfuscated' => 'Este objeto está oculto.',
            '::display:object:flag:unobfuscated' => 'Este objeto no está oculto.',
            '::display:object:flag:locked' => 'Esta entidad está bloqueada.',
            '::display:object:flag:unlocked' => 'Esta entidad está desbloqueada.',
            '::display:object:flag:activated' => 'Este objeto está activado.',
            '::display:object:flag:unactivated' => 'Este objeto no está activado.',
            '::list:empty' => 'Empty list',
            '::yes' => 'Si',
            '::no' => 'No',
            '::lock' => 'Locking',
            '::unlock' => 'Unlocking',
            '::entity:locked' => 'Entidad bloqueada. Desbloquear?',
            '::entity:unlocked' => 'Entidad desbloqueada. Bloquear?',
            '::allApplications' => 'Bootstrap and applications',
            '::Version' => 'Version',
            '::version' => 'version',
            '::UniqueID' => 'Universal identifier : %s',
            '::progress' => 'In progress...',
            '::seeMore' => 'See more...',
            '::noContent' => '(content not available)',
            '::appSwitch' => 'Switch application',
            '::menu' => 'Menu',
            '::menuDesc' => 'Page with full menu',
            '::EmptyList' => 'Empty list.',
            '::ChangeLanguage' => 'Cambiar el idioma',
            '::SelectUser' => 'Seleccionar un usuario',
            '::MarkAdd' => 'Mark',
            '::MarkRemove' => 'Unmark',
            '::MarkRemoveAll' => 'Unmark all',
            '::Synchronize' => 'Synchronize',
            '::notImplemented' => 'Not yet implemented...',
            '::notSupported' => 'Not supported...',
            '::password' => 'Password',
            '::login' => 'Conectando',
            '::confirm' => 'Confirmación',
            '::privateKey' => 'Private key',
            '::connexion' => 'Connection',
            '::logout' => 'Disconnecting',
            '::selfLogout' => 'Disconnecting myself',
            '::flush' => 'Disconnecting all',
            '::return' => 'Return to application',
            '::previousPage' => 'Previous page',
            '::nextPage' => 'Next page',
            '::page%s%s%s%s%s' => 'Page %s/%s (%s-%s en %s)',
            '::limitedType' => 'El tipo de miembros está limitado a "%s"',
            '::options' => 'Options',
            '::synchronize' => 'Synchronize',
            '::synchroAll' => 'Synchronize all',
            '::refreshList' => 'Refresh the list',

            // Groups
            '::group' => 'group',
            '::Group' => 'Group',
            '::closeGroup' => 'Closed group',
            '::openGroup' => 'Opened group',
            '::groups' => 'The groups',
            '::seeTheGroupNode' => 'See the group',
            '::seeTheGroupEntity' => 'See the group of entities',
            '::myGroupsNode' => 'My groups',
            '::myGroupsEntity' => 'My groups of entities',
            '::allGroupsNode' => 'All groups',
            '::allGroupsEntity' => 'All groups of entities',
            '::otherGroupsNode' => 'Groups of other entities',
            '::otherGroupsEntity' => 'Groups of other entities',
            '::createGroupNode' => 'Create a group',
            '::createGroupEntity' => 'Create a group of entities',
            '::createTheGroupNode' => 'Create the group',
            '::createTheGroupEntity' => 'Create the group',
            '::createGroupNodeOK' => 'The group have been created',
            '::createGroupEntityOK' => 'The group have been created',
            '::createGroupNodeNOK' => 'The group have not been created! %s',
            '::createGroupEntityNOK' => 'The group have not been created! %s',
            '::createClosedGroup' => 'Create a closed group',
            '::createObfuscatedGroup' => 'Create an obfuscated group',
            '::deleteGroup' => 'Delete the group',
            '::modifyGroupNode' => 'Modify the group',
            '::modifyGroupEntity' => 'Modify the group of entities',
            '::removeGroupNode' => 'Remove the group',
            '::removeGroupEntity' => 'Remove the group of entities',
            '::refuseGroupNode' => 'Refuse this object as group',
            '::refuseGroupEntity' => 'Refuse this object as group',
            '::getGroupNode' => 'Get a group',
            '::getGroupEntity' => 'Get a group of entities',
            '::returnToGroupNode' => 'Return to the group',
            '::returnToGroupEntity' => 'Return to the group',
            '::addMemberNode' => 'Add a member',
            '::addMemberEntity' => 'Add an entity as member',
            '::membersType' => 'Type of members',
            '::founder' => 'Founder',
            '::owner' => 'Owner',
            '::writer' => 'Writer',
            '::follower' => 'Follower',
            '::addAsOwner' => 'Add as owner',
            '::addAsWriter' => 'Add as writer',
            '::addAsFollower' => 'Add as follower',
            '::removeAsOwner' => 'Remove as owner',
            '::removeAsWriter' => 'Remove as writer',
            '::removeAsFollower' => 'Remove as follower',

            // Conversations
            '::conversation' => 'conversation',
            '::Conversation' => 'Conversation',
            '::closeConversation' => 'Closed conversation',
            '::openConversation' => 'Opened conversation',
            '::conversations' => 'The conversations',
            '::seeTheConversation' => 'See the conversation',
            '::myConversations' => 'My conversations',
            '::allConversations' => 'All conversations',
            '::otherConversations' => 'Conversations of other entities',
            '::createConversation' => 'Create a conversation',
            '::createTheConversation' => 'Create the conversation',
            '::createConversationOK' => 'The conversation have been created',
            '::createConversationNOK' => 'The conversation have not been created! %s',
            '::createClosedConversation' => 'Create a closed conversation',
            '::createObfuscatedConversation' => 'Create an obfuscated conversation',
            '::deleteConversation' => 'Delete the conversation',
            '::modifyConversation' => 'Modify the conversation',
            '::removeConversation' => 'Remove the conversation',
            '::refuseConversation' => 'Refuse this object as conversation',
            '::getConversation' => 'Get a conversation',
            '::returnToConversation' => 'Return to the conversation',

            // Folders
            '::rootFolder' => 'Root folder',
            '::closeRootFolder' => 'Closed root folder',
            '::openRootFolder' => 'Opened root folder',
            '::rootFolders' => 'The root folders',
            '::seeTheRootFolder' => 'See the root folder',
            '::myRootFolders' => 'My root folders',
            '::allRootFolders' => 'All root folders',
            '::otherRootFolders' => 'Root root folders of other entities',
            '::createRootFolder' => 'Create a root folder',
            '::createTheRootFolder' => 'Create the root folder',
            '::createRootFolderOK' => 'The root folder have been created',
            '::createRootFolderNOK' => 'The root folder have not been created! %s',
            '::createClosedRootFolder' => 'Create a closed root folder',
            '::createObfuscatedRootFolder' => 'Create an obfuscated root folder',
            '::deleteRootFolder' => 'Delete the root folder',
            '::modifyRootFolder' => 'Modify the root folder',
            '::removeRootFolder' => 'Remove the root folder',
            '::refuseRootFolder' => 'Refuse this object as root folder',
            '::getRootFolder' => 'Get a root folder',
            '::returnToRootFolder' => 'Return to the root folder',
            '::folder' => 'folder',
            '::Folder' => 'Folder',
            '::folders' => 'The folders',
            '::seeTheFolder' => 'See the folder',
            '::myFolders' => 'My folders',
            '::allFolders' => 'All folders',
            '::otherFolders' => 'Folders of other entities',
            '::addFolder' => 'Add a folder',
            '::createFolder' => 'Create a folder',
            '::createTheFolder' => 'Create the folder',
            '::createFolderOK' => 'The folder have been created',
            '::createFolderNOK' => 'The folder have not been created! %s',
            '::createObfuscatedFolder' => 'Create an obfuscated root folder',
            '::deleteFolder' => 'Delete the folder',
            '::modifyFolder' => 'Modify the folder',
            '::removeFolder' => 'Remove the folder',
            '::refuseFolder' => 'Refuse this object as folder',
            '::getFolder' => 'Get a folder',
            '::returnToFolder' => 'Return to the folder',
            '::addObject' => 'Add an object',

            // Galleries
            '::gallery' => 'gallery',
            '::Gallery' => 'Gallery',
            '::closeGallery' => 'Closed gallery',
            '::openGallery' => 'Opened gallery',
            '::galleries' => 'The galleries',
            '::seeTheGallery' => 'See the gallery',
            '::myGalleries' => 'My galleries',
            '::allGalleries' => 'All galleries',
            '::otherGalleries' => 'Galleries of other entities',
            '::createGallery' => 'Create a gallery',
            '::createTheGallery' => 'Create the gallery',
            '::createGalleryOK' => 'The gallery have been created',
            '::createGalleryNOK' => 'The gallery have not been created! %s',
            '::createClosedGallery' => 'Create a closed gallery',
            '::createObfuscatedGallery' => 'Create an obfuscated gallery',
            '::deleteGallery' => 'Delete the gallery',
            '::modifyGallery' => 'Modify the gallery',
            '::removeGallery' => 'Remove the gallery',
            '::refuseGallery' => 'Refuse this object as gallery',
            '::getGallery' => 'Get a gallery',
            '::returnToGallery' => 'Return to the gallery',

            // Blogs
            '::blog' => 'blog',
            '::Blog' => 'Blog',
            '::closeBlog' => 'Closed blog',
            '::openBlog' => 'Opened blog',
            '::blogs' => 'The blogs',
            '::seeTheBlog' => 'See the blog',
            '::myBlogs' => 'My blogs',
            '::allBlogs' => 'All blogs',
            '::otherBlogs' => 'Blogs of other entities',
            '::createBlog' => 'Create a blog',
            '::createTheBlog' => 'Create the blog',
            '::createBlogOK' => 'The blog have been created',
            '::createBlogNOK' => 'The blog have not been created! %s',
            '::createClosedBlog' => 'Create a closed blog',
            '::createObfuscatedBlog' => 'Create an obfuscated blog',
            '::deleteBlog' => 'Delete the blog',
            '::modifyBlog' => 'Modify the blog',
            '::removeBlog' => 'Remove the blog',
            '::refuseBlog' => 'Refuse this object as blog',
            '::getBlog' => 'Get a blog',
            '::returnToBlog' => 'Return to the blog',
        ],
    ];
}
