<?php
declare(strict_types=1);
namespace Nebule\Application\Modules;
use Nebule\Library\nebule;
use Nebule\Library\References;
use Nebule\Library\Metrology;
use Nebule\Library\Applications;
use Nebule\Library\Displays;
use Nebule\Library\Actions;
use Nebule\Library\Translates;
use Nebule\Library\ModuleInterface;
use Nebule\Library\Module;
use Nebule\Library\ModelModuleHelp;
use Nebule\Library\ModuleTranslates;

/**
 * Ce module permet la traduction en français FR-FR.
 *
 * @author Projet nebule
 * @license GNU GPLv3
 * @copyright Projet nebule
 * @link www.nebule.org
 */
class ModuleTranslateFRFR extends ModuleTranslates
{
    const MODULE_LANGUAGE = 'fr-fr';
    const MODULE_NAME = '::translateModule:fr-fr:ModuleName';
    const MODULE_MENU_NAME = '::translateModule:fr-fr:MenuName';
    const MODULE_DESCRIPTION = '::translateModule:fr-fr:ModuleDescription';
    const MODULE_VERSION = '020260110';
    const MODULE_AUTHOR = 'Projet nebule';
    const MODULE_LICENCE = 'GNU GLP v3 2013-2026';
    const MODULE_LOGO = 'b55cb8774839a5a894cecf77ce5e47db7fc114c2bc92e3dfc77cb9b4a8f488ac.sha2.256';
    const MODULE_INTERFACE = '3.0';
    CONST TRANSLATE_TABLE = [
        'en-en' => [
            '::translateModule:fr-fr:ModuleName' => 'French (France)',
            '::translateModule:fr-fr:MenuName' => 'French (France)',
            '::translateModule:fr-fr:ModuleDescription' => 'Interface translation in French.',
            '::translateModule:fr-fr:ModuleHelp' => 'This module permit to translate the nebule applications in French.',
        ],
        'fr-fr' => [
            '::translateModule:fr-fr:ModuleName' => 'Français (France)',
            '::translateModule:fr-fr:MenuName' => 'Français (France)',
            '::translateModule:fr-fr:ModuleDescription' => "Traduction de l'interface en Français.",
            '::translateModule:fr-fr:ModuleHelp' => "Ce module permet de mettre en place la traduction des applications de nebule en Français.",

            'nebule/objet' => 'Objet',
            'nebule/objet/hash' => "Type d'empreinte",
            'nebule/objet/type' => 'Type MIME',
            'nebule/objet/taille' => 'Taille',
            'nebule/objet/nom' => 'Nom',
            'nebule/objet/prefix' => 'Préfix',
            'nebule/objet/prenom' => 'Prénom',
            'nebule/objet/suffix' => 'Suffix',
            'nebule/objet/surnom' => 'Surnom',
            'nebule/objet/postnom' => 'Surnom',
            'nebule/objet/entite' => 'Entité',
            'nebule/objet/entite/type' => 'Type',
            'nebule/objet/date' => 'Date',
            'nebule/objet/date/annee' => 'Année',
            'nebule/objet/date/mois' => 'Mois',
            'nebule/objet/date/jour' => 'Jour',
            'nebule/objet/date/heure' => 'Heure',
            'nebule/objet/date/minute' => 'Minute',
            'nebule/objet/date/seconde' => 'Seconde',
            'nebule/objet/date/zone' => 'Zone de temps',
            'nebule/objet/emotion/colere' => 'Contrariant',
            'nebule/objet/emotion/degout' => 'Dégôuté',
            'nebule/objet/emotion/surprise' => 'Étonnant',
            'nebule/objet/emotion/peur' => 'Inquiétant',
            'nebule/objet/emotion/interet' => 'Intéressé',
            'nebule/objet/emotion/joie' => "J'aime",
            'nebule/objet/emotion/confiance' => "J'approuve",
            'nebule/objet/emotion/tristesse' => 'Tristement',
            'nebule/objet/entite/localisation' => 'Localisation',
            'nebule/objet/entite/maitre/securite' => 'Maître de la sécurité',
            'nebule/objet/entite/maitre/code' => 'Maître du code',
            'nebule/objet/entite/maitre/annuaire' => "Maître de l'annuaire",
            'nebule/objet/entite/maitre/temps' => 'Maître du temps',
            References::REFERENCE_OBJECT_TEXT => 'Texte brute',
            'application/x-pem-file' => 'Entité',
            'image/jpeg' => 'Image JPEG',
            'image/png' => 'Image PNG',
            'application/x-bzip2' => 'Archive BZIP2',
            'text/html' => 'Page HTML',
            'application/x-php' => 'Code PHP',
            'application/x-httpd-php' => 'Code PHP',
            'text/x-php' => 'Code PHP',
            'text/css' => 'Feuille de style CSS',
            'audio/mpeg' => 'Audio MP3',
            'audio/x-vorbis+ogg' => 'Audio OGG',
            'application/x-encrypted/rsa' => 'Chiffré',
            'application/x-encrypted/aes-256-ctr' => 'Chiffré',
            'application/x-folder' => 'Dossier',
            '::Welcome' => 'Bienvenue',
            '::INFO' => 'Information',
            '::OK' => 'OK',
            '::INFORMATION' => 'Message',
            '::WARN' => 'ATTENTION !',
            '::ERROR' => 'ERREUR !',
            '::RESCUE' => 'Mode de sauvetage !',
            '::GO' => 'Avancer',
            '::BACK' => 'Revenir',
            '::SecurityChecks' => 'Tests de sécurité',
            '::icon:DEFAULT_ICON_LO' => 'Objet',
            '::HtmlHeadDescription' => 'Application web pour nebule.',
            '::Experimental' => '[Experimental]',
            '::Developpement' => '[En cours de développement]',
            '::help' => 'Aide',
            '::IDprivateKey' => 'ID privé',
            '::IDpublicKey' => 'ID public',
            '::Password' => 'Mot de passe',
            '::Switch' => 'Commutateur',
            '::Query' => 'Question',
            '::node' => 'noeud',
            '::Node' => 'Noeud',
            '::entity' => 'entité',
            '::Entity' => 'Entité',
            '::location' => 'localisation',
            '::Location' => 'Localisation',
            '::currency' => 'monnaie',
            '::Currency' => 'Monnaie',
            '::tokenpool' => 'sac de jetons',
            '::Tokenpool' => 'Sac de jetons',
            '::token' => 'jeton',
            '::Token' => 'Jeton',
            '::wallet' => 'porte monnaie',
            '::Wallet' => 'Porte monnaie',
            '::display:content:errorBan' => 'Cet objet est banni, il ne peut pas être affiché !',
            '::display:content:warningTaggedWarning' => 'Cet objet est marqué comme dangereux, attention à son contenu !',
            '::display:content:ObjectProctected' => 'Cet objet est protégé !',
            '::display:content:warningObjectProctected' => 'Cet objet est marqué comme protégé, attention à la divulgation de son contenu en public !!!',
            '::display:content:OK' => "Le contenu de l'objet est valide.",
            '::display:content:warningTooBig' => "Cet objet est trop volumineux, son contenu n'a pas été vérifié !",
            '::display:content:errorNotDisplayable' => 'Cet objet ne peut pas être affiché !',
            '::display:content:errorNotAvailable' => "Cet objet n'est pas disponible, il ne peut pas être affiché !",
            '::display:content:notAnObject' => "Cet objet de référence n'a pas de contenu.",
            '::display:content:ObjectHaveUpdate' => 'Cet objet a été mis à jour vers :',
            '::display:content:Activated' => 'Cet objet est activé.',
            '::display:content:NotActivated' => 'Cet objet est désactivé.',
            '::display:link:OK' => 'Ce lien est valide.',
            '::display:link:errorInvalid' => "Ce lien n'est pas valide !",
            '::warn_ServNotPermitWrite' => "Ce serveur n'autorise pas les modifications.",
            '::warn_flushSessionAndCache' => "Toutes les données de connexion ont été effacées.",
            '::err_NotPermit' => 'Non autorisé sur ce serveur !',
            '::err_NoPrivKey' => 'Pas de clé privée !',
            '::act_chk_errCryptHash' => "La fonction de prise d'empreinte cryptographique ne fonctionne pas correctement !",
            '::act_chk_warnCryptHashkey' => "La taille de l'empreinte cryptographique est trop petite !",
            '::act_chk_errCryptHashkey' => "La taille de l'empreinte cryptographique est invalide !",
            '::act_chk_errCryptSym' => "La fonction de chiffrement cryptographique symétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est trop petite !",
            '::act_chk_errCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est invalide !",
            '::act_chk_errCryptAsym' => "La fonction de chiffrement cryptographique asymétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est trop petite !",
            '::act_chk_errCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est invalide !",
            '::act_chk_errBootstrap' => "L'empreinte cryptographique du bootstrap est invalide !",
            '::act_chk_warnSigns' => 'La vérification des signatures de liens est désactivée !',
            '::act_chk_errSigns' => 'La vérification des signatures de liens ne fonctionne pas !',
            '::info_OnlySignedLinks' => 'Uniquement des liens signés !',
            '::info_OnlyLinksFromCodeMaster' => 'Uniquement les liens signés du maître du code !',
            '::display:object:flag:protected' => 'Cet objet est protégé.',
            '::display:object:flag:unprotected' => "Cet objet n'est pas protégé.",
            '::display:object:flag:obfuscated' => 'Cet objet est dissimulé.',
            '::display:object:flag:unobfuscated' => "Cet objet n'est pas dissimulé.",
            '::display:object:flag:locked' => 'Cet entité est verrouillée.',
            '::display:object:flag:unlocked' => 'Cet entité est déverrouillée.',
            '::display:object:flag:activated' => 'Cet objet est activé.',
            '::display:object:flag:unactivated' => "Cet objet n'est pas activé.",
            '::list:empty' => 'Liste vide',
            '::yes' => 'Oui',
            '::no' => 'Non',
            '::lock' => 'Verrouiller',
            '::unlock' => 'Déverrouiller',
            '::entity:locked' => 'Entité verrouillée. Déverrouiller ?',
            '::entity:unlocked' => 'Entité déverrouillée. Verrouiller ?',
            '::allApplications' => 'Bootstrap et applications',
            '::Version' => 'Version',
            '::version' => 'version',
            '::UniqueID' => 'Identifiant universel : %s',
            '::progress' => 'Chargement en cours...',
            '::seeMore' => 'Voir plus...',
            '::noContent' => '(contenu indisponible)',
            '::appSwitch' => "Changer d'application",
            '::menu' => 'Menu',
            '::menuDesc' => 'Page du menu complet',
            '::EmptyList' => 'Liste vide.',
            '::ChangeLanguage' => 'Changer de langue',
            '::SelectUser' => 'Sélectionner un utilisateur',
            '::MarkAdd' => 'Marquer',
            '::MarkRemove' => 'Démarquer',
            '::MarkRemoveAll' => 'Démarquer tout',
            '::Synchronize' => 'Synchroniser',
            '::notImplemented' => 'Non encore implémenté...',
            '::notSupported' => 'Non supporté...',
            '::password' => 'Mot de passe',
            '::login' => 'Se connecter',
            '::confirm' => 'Confirmation',
            '::privateKey' => 'Clé privée',
            '::connexion' => 'Connexion',
            '::logout' => 'Déconnecter',
            '::selfLogout' => 'Se déconnecter',
            '::flush' => 'Tout déconnecter',
            '::return' => "Revenir à l'application",
            '::previousPage' => 'Page précédente',
            '::nextPage' => 'Page suivante',
            '::page%s%s%s%s%s' => 'Page %s/%s (%s-%s sur %s)',
            '::limitedType' => 'Le type des membres est limité à "%s"',
            '::options' => 'Options',
            '::rights' => 'Droits',
            '::synchronize' => 'Synchroniser',
            '::synchroAll' => 'Synchroniser tout',
            '::refreshList' => 'Rafraîchir la liste',
            '::nid' => "Empreinte de l'objet",

            // errors
            '::9a0b2492' => 'Canot create node for uploaded file.',
            '::7e720681' => 'The uploaded file exceeds the max filesize.',
            '::0a2485f6' => 'No uploaded file.',
            '::49eedd04' => 'The uploaded file exceeds the upload_max_filesize directive in php.ini.',
            '::e3a3864c' => 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form.',
            '::4555fd63' => 'The uploaded file was only partially uploaded.',
            '::27d21ac9' => 'No file was uploaded.',
            '::5e464992' => 'Missing a temporary folder.',
            '::3ab22f3a' => 'Failed to write file to disk.',
            '::e3c9845c' => 'A PHP extension stopped the file upload. PHP does not provide a way to ascertain which extension caused the file upload to stop.',

            // Groups
            '::group' => 'groupe',
            '::Group' => 'Groupe',
            '::closeGroup' => 'Groupe fermé',
            '::openGroup' => 'Groupe ouvert',
            '::groups' => 'Les groupes',
            '::seeTheGroupNode' => 'Voir le groupe',
            '::seeTheGroupEntity' => "Voir le groupe d'entités",
            '::myGroupsNode' => 'Mes groupes',
            '::myGroupsEntity' => "Mes groupes d'entités",
            '::allGroupsNode' => 'Tous les groupes',
            '::allGroupsEntity' => "Tous les groupes d'entités",
            '::otherGroupsNode' => 'Groupes des autres entités',
            '::otherGroupsEntity' => 'Groupes des autres entités',
            '::createGroupNode' => 'Créer un groupe',
            '::createGroupEntity' => "Créer un groupe d'entités",
            '::createTheGroupNode' => 'Créer le groupe',
            '::createTheGroupEntity' => 'Créer le groupe',
            '::createGroupNodeOK' => 'Le groupe a été créé',
            '::createGroupEntityOK' => 'Le groupe a été créé',
            '::createGroupNodeNOK' => "Le groupe n'a pas été créé ! %s",
            '::createGroupEntityNOK' => "Le groupe n'a pas été créé ! %s",
            '::createClosedGroup' => 'Créer un groupe fermé',
            '::createObfuscatedGroup' => 'Créer un groupe dissimulé',
            '::deleteGroup' => 'Supprimer le groupe',
            '::modifyGroupNode' => 'Modifier le groupe',
            '::modifyGroupEntity' => "Modifier le groupe",
            '::removeGroupNode' => 'Retirer le groupe',
            '::removeGroupEntity' => "Retirer le groupe d'entités",
            '::refuseGroupNode' => 'Refuser cet objet comme un groupe',
            '::refuseGroupEntity' => 'Refuser cet objet comme un groupe',
            '::getGroupNode' => 'Récupérer un groupe',
            '::getGroupEntity' => "Récupérer un groupe d'entités",
            '::returnToGroupNode' => 'Retourner au groupe',
            '::returnToGroupEntity' => 'Retourner au groupe',
            '::addMemberNode' => 'Ajouter un membre',
            '::addMemberEntity' => 'Ajouter une entité membre',
            '::membersType' => 'Type de membres :',
            '::founder' => 'Fondateur',
            '::owner' => 'Propriétaire',
            '::writer' => 'Écrivain',
            '::follower' => 'Abonné',
            '::addAsOwner' => 'Ajouter comme propriétaire',
            '::addAsWriter' => 'Ajouter comme écrivain',
            '::addAsFollower' => 'Ajouter comme abonné',
            '::removeAsOwner' => 'Retirer des propriétaires',
            '::removeAsWriter' => 'Retirer des écrivains',
            '::removeAsFollower' => 'Retirer des abonnés',

            // Conversations
            '::conversation' => 'conversation',
            '::Conversation' => 'Conversation',
            '::closeConversation' => 'Conversation fermée',
            '::openConversation' => 'Conversation ouverte',
            '::conversations' => 'Les conversations',
            '::seeTheConversation' => 'Voir la conversation',
            '::myConversations' => 'Mes conversations',
            '::allConversations' => 'Toutes les conversations',
            '::otherConversations' => 'Conversations des autres entités',
            '::createConversation' => 'Créer une conversation',
            '::createTheConversation' => 'Créer la conversation',
            '::createConversationOK' => 'La conversation a été créée',
            '::createConversationNOK' => "La conversation n'a pas été créée ! %s",
            '::createClosedConversation' => 'Créer une conversation fermée',
            '::createObfuscatedConversation' => 'Créer une conversation dissimulée',
            '::deleteConversation' => 'Supprimer la conversation',
            '::modifyConversation' => 'Modifier la conversation',
            '::removeConversation' => 'Retirer la conversation',
            '::refuseConversation' => 'Refuser cet objet comme conversation',
            '::getConversation' => 'Récupérer une conversation',
            '::returnToConversation' => 'Retourner à la conversation',

            // Folders
            '::rootFolder' => 'Dossier racine',
            '::closeRootFolder' => 'Dossier racine fermé',
            '::openRootFolder' => 'Dossier racine ouvert',
            '::rootFolders' => 'Les dossiers racines',
            '::seeTheRootFolder' => 'Voir le dossier racine',
            '::myRootFolders' => 'Mes dossiers racines',
            '::allRootFolders' => 'Tous les dossiers racines',
            '::otherRootFolders' => 'Dossiers racines des autres entités',
            '::createRootFolder' => 'Créer un dossier racine',
            '::createTheRootFolder' => 'Créer le dossier racine',
            '::createRootFolderOK' => 'Le dossier racine a été créé',
            '::createRootFolderNOK' => "Le dossier racine n'a pas été créé ! %s",
            '::createClosedRootFolder' => 'Créer un dossier racine fermé',
            '::createObfuscatedRootFolder' => 'Créer un dossier racine dissimulé',
            '::deleteRootFolder' => 'Supprimer le dossier racine',
            '::modifyRootFolder' => 'Modifier le dossier racine',
            '::removeRootFolder' => 'Retirer le dossier racine',
            '::refuseRootFolder' => 'Refuser cet objet comme dossier racine',
            '::getRootFolder' => 'Récupérer un dossier racine',
            '::returnToRootFolder' => 'Retourner au dossier racine',
            '::folder' => 'dossier',
            '::Folder' => 'Dossier',
            '::folders' => 'Les dossiers',
            '::seeTheFolder' => 'Voir le dossier',
            '::myFolders' => 'Mes dossiers',
            '::allFolders' => 'Tous les dossiers',
            '::otherFolders' => 'Dossiers des autres entités',
            '::addFolder' => 'Ajouter un dossier',
            '::createFolder' => 'Créer un dossier',
            '::createTheFolder' => 'Créer le dossier',
            '::createFolderOK' => 'Le dossier a été créé',
            '::createFolderNOK' => "Le dossier n'a pas été créé ! %s",
            '::createObfuscatedFolder' => 'Créer un dossier dissimulé',
            '::createProtectedNode' => 'Create a protected node',
            '::createObfuscatedNode' => 'Create an obfuscated node',
            '::deleteFolder' => 'Supprimer le dossier',
            '::modifyFolder' => 'Modifier le dossier',
            '::removeFolder' => 'Retirer le dossier',
            '::refuseFolder' => 'Refuser cet objet comme dossier',
            '::getFolder' => 'Récupérer un dossier',
            '::returnToFolder' => 'Retourner au dossier',
            '::addObject' => 'Ajouter un objet',
            '::addFile' => 'Ajouter un fichier',
            '::seeTheFile' => 'Voir le fichier',

            // Galleries
            '::gallery' => 'galerie',
            '::Gallery' => 'Galerie',
            '::closeGallery' => 'Galerie fermée',
            '::openGallery' => 'Galerie ouverte',
            '::galleries' => 'Les galeries',
            '::seeTheGallery' => 'Voir la galerie',
            '::myGalleries' => 'Mes galeries',
            '::allGalleries' => 'Toutes les galeries',
            '::otherGalleries' => 'Galeries des autres entités',
            '::createGallery' => 'Créer une galerie',
            '::createTheGallery' => 'Créer la galerie',
            '::createGalleryOK' => 'La galerie a été créée',
            '::createGalleryNOK' => "La galerie n'a pas été créée ! %s",
            '::createClosedGallery' => 'Créer une galerie fermée',
            '::createObfuscatedGallery' => 'Créer une galerie dissimulée',
            '::deleteGallery' => 'Supprimer la galerie',
            '::modifyGallery' => 'Modifier la galerie',
            '::removeGallery' => 'Retirer la galerie',
            '::refuseGallery' => 'Refuser cet objet comme galerie',
            '::getGallery' => 'Récupérer une galerie',
            '::returnToGallery' => 'Retourner à la galerie',

            // Blogs
            '::blog' => 'blog',
            '::Blog' => 'Blog',
            '::closeBlog' => 'Blog fermé',
            '::openBlog' => 'Blog ouvert',
            '::blogs' => 'Les blogs',
            '::seeTheBlog' => 'Voir le blog',
            '::myBlogs' => 'Mes blogs',
            '::allBlogs' => 'Tous les blogs',
            '::otherBlogs' => 'Blogs des autres entités',
            '::createBlog' => 'Créer un blog',
            '::createTheBlog' => 'Créer le blog',
            '::createBlogOK' => 'Le blog a été créé',
            '::createBlogNOK' => "Le blog n'a pas été créé ! %s",
            '::createClosedBlog' => 'Créer un blog fermé',
            '::createObfuscatedBlog' => 'Créer un blog dissimulé',
            '::deleteBlog' => 'Supprimer le blog',
            '::modifyBlog' => 'Modifier le blog',
            '::removeBlog' => 'Retirer le blog',
            '::refuseBlog' => 'Refuser cet objet comme blog',
            '::getBlog' => 'Récupérer un blog',
            '::returnToBlog' => 'Retourner au blog',
        ],
    ];
}
