<?php
declare(strict_types=1);
namespace Nebule\Application\Modules;
use Nebule\Library\nebule;
use Nebule\Library\References;
use Nebule\Library\Metrology;
use Nebule\Library\Applications;
use Nebule\Library\Displays;
use Nebule\Library\Actions;
use Nebule\Library\Translates;
use Nebule\Library\ModuleInterface;
use Nebule\Library\Module;
use Nebule\Library\ModelModuleHelp;
use Nebule\Library\ModuleTranslates;

/**
 * Ce module permet la traduction en français FR-FR.
 *
 * @author Projet nebule
 * @license GNU GPLv3
 * @copyright Projet nebule
 * @link www.nebule.org
 */
class ModuleTranslateFRFR extends ModuleTranslates
{
    const MODULE_LANGUAGE = 'fr-fr';
    const MODULE_NAME = '::translateModule:fr-fr:ModuleName';
    const MODULE_MENU_NAME = '::translateModule:fr-fr:MenuName';
    const MODULE_DESCRIPTION = '::translateModule:fr-fr:ModuleDescription';
    const MODULE_VERSION = '020260104';
    const MODULE_AUTHOR = 'Projet nebule';
    const MODULE_LICENCE = 'GNU GLP v3 2013-2026';
    const MODULE_LOGO = 'b55cb8774839a5a894cecf77ce5e47db7fc114c2bc92e3dfc77cb9b4a8f488ac.sha2.256';
    const MODULE_INTERFACE = '3.0';
    CONST TRANSLATE_TABLE = [
        'en-en' => [
            '::translateModule:fr-fr:ModuleName' => 'French (France)',
            '::translateModule:fr-fr:MenuName' => 'French (France)',
            '::translateModule:fr-fr:ModuleDescription' => 'Interface translation in French.',
            '::translateModule:fr-fr:ModuleHelp' => 'This module permit to translate the nebule applications in French.',
        ],
        'fr-fr' => [
            '::translateModule:fr-fr:ModuleName' => 'Français (France)',
            '::translateModule:fr-fr:MenuName' => 'Français (France)',
            '::translateModule:fr-fr:ModuleDescription' => "Traduction de l'interface en Français.",
            '::translateModule:fr-fr:ModuleHelp' => "Ce module permet de mettre en place la traduction des applications de nebule en Français.",

            'nebule/objet' => 'Objet',
            'nebule/objet/hash' => "Type d'empreinte",
            'nebule/objet/type' => 'Type MIME',
            'nebule/objet/taille' => 'Taille',
            'nebule/objet/nom' => 'Nom',
            'nebule/objet/prefix' => 'Préfix',
            'nebule/objet/prenom' => 'Prénom',
            'nebule/objet/suffix' => 'Suffix',
            'nebule/objet/surnom' => 'Surnom',
            'nebule/objet/postnom' => 'Surnom',
            'nebule/objet/entite' => 'Entité',
            'nebule/objet/entite/type' => 'Type',
            'nebule/objet/date' => 'Date',
            'nebule/objet/date/annee' => 'Année',
            'nebule/objet/date/mois' => 'Mois',
            'nebule/objet/date/jour' => 'Jour',
            'nebule/objet/date/heure' => 'Heure',
            'nebule/objet/date/minute' => 'Minute',
            'nebule/objet/date/seconde' => 'Seconde',
            'nebule/objet/date/zone' => 'Zone de temps',
            'nebule/objet/emotion/colere' => 'Contrariant',
            'nebule/objet/emotion/degout' => 'Dégôuté',
            'nebule/objet/emotion/surprise' => 'Étonnant',
            'nebule/objet/emotion/peur' => 'Inquiétant',
            'nebule/objet/emotion/interet' => 'Intéressé',
            'nebule/objet/emotion/joie' => "J'aime",
            'nebule/objet/emotion/confiance' => "J'approuve",
            'nebule/objet/emotion/tristesse' => 'Tristement',
            'nebule/objet/entite/localisation' => 'Localisation',
            'nebule/objet/entite/maitre/securite' => 'Maître de la sécurité',
            'nebule/objet/entite/maitre/code' => 'Maître du code',
            'nebule/objet/entite/maitre/annuaire' => "Maître de l'annuaire",
            'nebule/objet/entite/maitre/temps' => 'Maître du temps',
            References::REFERENCE_OBJECT_TEXT => 'Texte brute',
            'application/x-pem-file' => 'Entité',
            'image/jpeg' => 'Image JPEG',
            'image/png' => 'Image PNG',
            'application/x-bzip2' => 'Archive BZIP2',
            'text/html' => 'Page HTML',
            'application/x-php' => 'Code PHP',
            'application/x-httpd-php' => 'Code PHP',
            'text/x-php' => 'Code PHP',
            'text/css' => 'Feuille de style CSS',
            'audio/mpeg' => 'Audio MP3',
            'audio/x-vorbis+ogg' => 'Audio OGG',
            'application/x-encrypted/rsa' => 'Chiffré',
            'application/x-encrypted/aes-256-ctr' => 'Chiffré',
            'application/x-folder' => 'Dossier',
            '::Welcome' => 'Bienvenue',
            '::INFO' => 'Information',
            '::OK' => 'OK',
            '::INFORMATION' => 'Message',
            '::WARN' => 'ATTENTION !',
            '::ERROR' => 'ERREUR !',
            '::RESCUE' => 'Mode de sauvetage !',
            '::GO' => 'Avancer',
            '::BACK' => 'Revenir',
            '::SecurityChecks' => 'Tests de sécurité',
            '::icon:DEFAULT_ICON_LO' => 'Objet',
            '::HtmlHeadDescription' => 'Page web cliente sylabe pour nebule.',
            '::Experimental' => '[Experimental]',
            '::Developpement' => '[En cours de développement]',
            '::help' => 'Aide',
            '::IDprivateKey' => 'ID privé',
            '::IDpublicKey' => 'ID public',
            '::Password' => 'Mot de passe',
            '::Switch' => 'Commutateur',
            '::Query' => 'Question',
            '::node' => 'noeud',
            '::Node' => 'Noeud',
            '::group' => 'groupe',
            '::Group' => 'Groupe',
            '::entity' => 'entité',
            '::Entity' => 'Entité',
            '::location' => 'localisation',
            '::Location' => 'Localisation',
            '::conversation' => 'conversation',
            '::Conversation' => 'Conversation',
            '::currency' => 'monnaie',
            '::Currency' => 'Monnaie',
            '::tokenpool' => 'sac de jetons',
            '::Tokenpool' => 'Sac de jetons',
            '::token' => 'jeton',
            '::Token' => 'Jeton',
            '::wallet' => 'porte monnaie',
            '::Wallet' => 'Porte monnaie',
            '::display:content:errorBan' => 'Cet objet est banni, il ne peut pas être affiché !',
            '::display:content:warningTaggedWarning' => 'Cet objet est marqué comme dangereux, attention à son contenu !',
            '::display:content:ObjectProctected' => 'Cet objet est protégé !',
            '::display:content:warningObjectProctected' => 'Cet objet est marqué comme protégé, attention à la divulgation de son contenu en public !!!',
            '::display:content:OK' => "Le contenu de l'objet est valide.",
            '::display:content:warningTooBig' => "Cet objet est trop volumineux, son contenu n'a pas été vérifié !",
            '::display:content:errorNotDisplayable' => 'Cet objet ne peut pas être affiché !',
            '::display:content:errorNotAvailable' => "Cet objet n'est pas disponible, il ne peut pas être affiché !",
            '::display:content:notAnObject' => "Cet objet de référence n'a pas de contenu.",
            '::display:content:ObjectHaveUpdate' => 'Cet objet a été mis à jour vers :',
            '::display:content:Activated' => 'Cet objet est activé.',
            '::display:content:NotActivated' => 'Cet objet est désactivé.',
            '::display:link:OK' => 'Ce lien est valide.',
            '::display:link:errorInvalid' => "Ce lien n'est pas valide !",
            '::warn_ServNotPermitWrite' => "Ce serveur n'autorise pas les modifications.",
            '::warn_flushSessionAndCache' => "Toutes les données de connexion ont été effacées.",
            '::err_NotPermit' => 'Non autorisé sur ce serveur !',
            '::act_chk_errCryptHash' => "La fonction de prise d'empreinte cryptographique ne fonctionne pas correctement !",
            '::act_chk_warnCryptHashkey' => "La taille de l'empreinte cryptographique est trop petite !",
            '::act_chk_errCryptHashkey' => "La taille de l'empreinte cryptographique est invalide !",
            '::act_chk_errCryptSym' => "La fonction de chiffrement cryptographique symétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est trop petite !",
            '::act_chk_errCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est invalide !",
            '::act_chk_errCryptAsym' => "La fonction de chiffrement cryptographique asymétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est trop petite !",
            '::act_chk_errCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est invalide !",
            '::act_chk_errBootstrap' => "L'empreinte cryptographique du bootstrap est invalide !",
            '::act_chk_warnSigns' => 'La vérification des signatures de liens est désactivée !',
            '::act_chk_errSigns' => 'La vérification des signatures de liens ne fonctionne pas !',
            '::info_OnlySignedLinks' => 'Uniquement des liens signés !',
            '::info_OnlyLinksFromCodeMaster' => 'Uniquement les liens signés du maître du code !',
            '::display:object:flag:protected' => 'Cet objet est protégé.',
            '::display:object:flag:unprotected' => "Cet objet n'est pas protégé.",
            '::display:object:flag:obfuscated' => 'Cet objet est dissimulé.',
            '::display:object:flag:unobfuscated' => "Cet objet n'est pas dissimulé.",
            '::display:object:flag:locked' => 'Cet entité est verrouillée.',
            '::display:object:flag:unlocked' => 'Cet entité est déverrouillée.',
            '::display:object:flag:activated' => 'Cet objet est activé.',
            '::display:object:flag:unactivated' => "Cet objet n'est pas activé.",
            '::list:empty' => 'Liste vide',
            '::yes' => 'Oui',
            '::no' => 'Non',
            '::lock' => 'Verrouiller',
            '::unlock' => 'Déverrouiller',
            '::entity:locked' => 'Entité verrouillée. Déverrouiller ?',
            '::entity:unlocked' => 'Entité déverrouillée. Verrouiller ?',
            '::allApplications' => 'Bootstrap et applications',
            '::Version' => 'Version',
            '::UniqueID' => 'Identifiant universel : %s',
            '::GroupeFerme' => 'Groupe fermé',
            '::GroupeOuvert' => 'Groupe ouvert',
            '::ConversationFermee' => 'Conversation fermée',
            '::ConversationOuverte' => 'Conversation ouverte',
            '::progress' => 'Chargement en cours...',
            '::seeMore' => 'Voir plus...',
            '::noContent' => '(contenu indisponible)',
            '::appSwitch' => "Changer d'application",
            '::menu' => 'Menu',
            '::menuDesc' => 'Page du menu complet',
            '::EmptyList' => 'Liste vide.',
            '::ChangeLanguage' => 'Changer de langue',
            '::SelectUser' => 'Sélectionner un utilisateur',
            '::MarkAdd' => 'Marquer',
            '::MarkRemove' => 'Démarquer',
            '::MarkRemoveAll' => 'Démarquer tout',
            '::Synchronize' => 'Synchroniser',
            '::notImplemented' => 'Non encore implémenté...',
            '::notSupported' => 'Non supporté...',
            '::password' => 'Mot de passe',
            '::login' => 'Se connecter',
            '::confirm' => 'Confirmation',
            '::privateKey' => 'Clé privée',
            '::connexion' => 'Connexion',
            '::logout' => 'Déconnecter',
            '::selfLogout' => 'Se déconnecter',
            '::flush' => 'Tout déconnecter',
            '::return' => "Revenir à l'application",
            '::err_NoPrivKey' => 'Pas de clé privée !',
            '::previousPage' => 'Page précédente',
            '::nextPage' => 'Page suivante',
            '::page%s%s%s%s%s' => 'Page %s/%s (%s-%s sur %s)',
            '::limitedType' => 'Le type des membres est limité à "%s"',
        ],
    ];
}
