<?php
declare(strict_types=1);
namespace Nebule\Application\Modules;
use Nebule\Library\nebule;
use Nebule\Library\References;
use Nebule\Library\Metrology;
use Nebule\Library\Applications;
use Nebule\Library\Displays;
use Nebule\Library\Actions;
use Nebule\Library\Translates;
use Nebule\Library\ModuleInterface;
use Nebule\Library\Module;
use Nebule\Library\ModelModuleHelp;
use Nebule\Library\ModuleTranslates;

/**
 * This module adds translation in German DE-DE.
 *
 * @author Projet nebule
 * @license GNU GPLv3
 * @copyright Projet nebule
 * @link www.nebule.org
 */
class ModuleTranslateDEDE extends ModuleTranslates
{
    const MODULE_LANGUAGE = 'de-de';
    const MODULE_NAME = '::translateModule:de-de:ModuleName';
    const MODULE_MENU_NAME = '::translateModule:de-de:MenuName';
    const MODULE_DESCRIPTION = '::translateModule:de-de:ModuleDescription';
    const MODULE_VERSION = '020260110';
    const MODULE_AUTHOR = 'Projet nebule';
    const MODULE_LICENCE = 'GNU GLP v3 2013-2026';
    const MODULE_LOGO = '66af532d9627b29e83e4a55d518eec5be73ebec31e82ec5d5d1315b32e68ad3f.sha2.256';
    const MODULE_INTERFACE = '3.0';
    CONST TRANSLATE_TABLE = [
        'de-de' => [
            '::translateModule:de-de:ModuleName' => 'Deutsch (Deutschland)',
            '::translateModule:de-de:MenuName' => 'Deutsch (Deutschland)',
            '::translateModule:de-de:ModuleDescription' => 'Schnittstellenübersetzung auf Deutsch.',
            '::translateModule:de-de:ModuleHelp' => 'Dieses Modul ermöglicht es, die nebule-Anwendungen ins Deutsche zu übersetzen.',

            'nebule/objet' => 'Object',
            'nebule/objet/hash' => 'Hash type',
            'nebule/objet/type' => 'MIME type',
            'nebule/objet/taille' => 'Size',
            'nebule/objet/nom' => 'Name',
            'nebule/objet/prefix' => 'Prefix',
            'nebule/objet/prenom' => 'First name',
            'nebule/objet/suffix' => 'Suffix',
            'nebule/objet/surnom' => 'Nickname',
            'nebule/objet/postnom' => 'Nickname',
            'nebule/objet/entite' => 'Entity',
            'nebule/objet/entite/type' => 'Type',
            'nebule/objet/date' => 'Date',
            'nebule/objet/date/annee' => 'Year',
            'nebule/objet/date/mois' => 'Month',
            'nebule/objet/date/jour' => 'Day',
            'nebule/objet/date/heure' => 'Hour',
            'nebule/objet/date/minute' => 'Minute',
            'nebule/objet/date/seconde' => 'Second',
            'nebule/objet/date/zone' => 'Zone de temps',
            'nebule/objet/emotion/colere' => 'Annoying',
            'nebule/objet/emotion/degout' => 'Bummed',
            'nebule/objet/emotion/surprise' => 'Surprised',
            'nebule/objet/emotion/peur' => 'disturbed',
            'nebule/objet/emotion/interet' => 'Interested',
            'nebule/objet/emotion/joie' => 'I like',
            'nebule/objet/emotion/confiance' => 'Agree',
            'nebule/objet/emotion/tristesse' => 'Sadly',
            'nebule/objet/entite/localisation' => 'Localisation',
            'nebule/objet/entite/maitre/securite' => 'Master of security',
            'nebule/objet/entite/maitre/code' => 'Master of code',
            'nebule/objet/entite/maitre/annuaire' => 'Master of directory',
            'nebule/objet/entite/maitre/temps' => 'Master of time',
            References::REFERENCE_OBJECT_TEXT => 'RAW text',
            'application/x-pem-file' => 'Entity',
            'image/jpeg' => 'JPEG picture',
            'image/png' => 'PNG picture',
            'application/x-bzip2' => 'Archive BZIP2',
            'text/html' => 'HTML page',
            'application/x-php' => 'PHP code',
            'application/x-httpd-php' => 'PHP code',
            'text/x-php' => 'PHP code',
            'text/css' => 'Cascading Style Sheet CSS',
            'audio/mpeg' => 'Audio MP3',
            'audio/x-vorbis+ogg' => 'Audio OGG',
            'application/x-encrypted/rsa' => 'Encrypted',
            'application/x-encrypted/aes-256-ctr' => 'Encrypted',
            'application/x-folder' => 'Folder',
            '::Welcome' => 'Welcome',
            '::INFO' => 'Information',
            '::OK' => 'OK',
            '::INFORMATION' => 'Message',
            '::WARN' => 'WARNING!',
            '::ERROR' => 'ERROR!',
            '::RESCUE' => 'Rescue mode!',
            '::GO' => 'Continue',
            '::BACK' => 'Go back',
            '::SecurityChecks' => 'Security checks',
            '::icon:DEFAULT_ICON_LO' => 'Object',
            '::HtmlHeadDescription' => 'Client web page sylabe for nebule.',
            '::Experimental' => '[Experimental]',
            '::Developpement' => '[Under developpement]',
            '::help' => 'Help',
            '::IDprivateKey' => 'Private ID',
            '::IDpublicKey' => 'Public ID',
            '::Password' => 'Password',
            '::Switch' => 'Switching',
            '::Query' => 'Query',
            '::node' => 'node',
            '::Node' => 'Node',
            '::entity' => 'entity',
            '::Entity' => 'Entity',
            '::location' => 'location',
            '::Location' => 'Location',
            '::currency' => 'currency',
            '::Currency' => 'Currency',
            '::tokenpool' => 'token pool',
            '::Tokenpool' => 'Token pool',
            '::token' => 'token',
            '::Token' => 'Token',
            '::wallet' => 'wallet',
            '::Wallet' => 'Wallet',
            '::display:content:errorBan' => "This object is banned, it can't be displayed!",
            '::display:content:warningTaggedWarning' => "This object is marked as dangerous, be carfull with it's content!",
            '::display:content:ObjectProctected' => "This object is marked as protected!",
            '::display:content:warningObjectProctected' => "This object is marked as protected, be careful when it's content is displayed in public!",
            '::display:content:OK' => 'The object content is valid.',
            '::display:content:warningTooBig' => "This object is too big, it's content have not been checked!",
            '::display:content:errorNotDisplayable' => "This object can't be displayed!",
            '::display:content:errorNotAvailable' => "This object is not available, it can't be displayed!",
            '::display:content:notAnObject' => 'This reference object do not have content.',
            '::display:content:ObjectHaveUpdate' => 'This object have been updated to:',
            '::display:content:Activated' => 'This object is activated.',
            '::display:content:NotActivated' => 'This object is not activated.',
            '::display:link:OK' => 'This link is valid.',
            '::display:link:errorInvalid' => 'This link is invalid!',
            '::warn_ServNotPermitWrite' => 'This server do not permit modifications.',
            '::warn_flushSessionAndCache' => 'All datas of this connexion have been flushed.',
            '::err_NotPermit' => 'Non autorisé sur ce serveur !',
            '::err_NoPrivKey' => 'No private key!',
            '::act_chk_errCryptHash' => "La fonction de prise d'empreinte cryptographique ne fonctionne pas correctement !",
            '::act_chk_warnCryptHashkey' => "La taille de l'empreinte cryptographique est trop petite !",
            '::act_chk_errCryptHashkey' => "La taille de l'empreinte cryptographique est invalide !",
            '::act_chk_errCryptSym' => "La fonction de chiffrement cryptographique symétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est trop petite !",
            '::act_chk_errCryptSymkey' => "La taille de clé de chiffrement cryptographique symétrique est invalide !",
            '::act_chk_errCryptAsym' => "La fonction de chiffrement cryptographique asymétrique ne fonctionne pas correctement !",
            '::act_chk_warnCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est trop petite !",
            '::act_chk_errCryptAsymkey' => "La taille de clé de chiffrement cryptographique asymétrique est invalide !",
            '::act_chk_errBootstrap' => "L'empreinte cryptographique du bootstrap est invalide !",
            '::act_chk_warnSigns' => 'La vérification des signatures de liens est désactivée !',
            '::act_chk_errSigns' => 'La vérification des signatures de liens ne fonctionne pas !',
            '::info_OnlySignedLinks' => 'Only signed links!',
            '::info_OnlyLinksFromCodeMaster' => 'Only links signed by the code master!',
            '::display:object:flag:protected' => 'This object is protected.',
            '::display:object:flag:unprotected' => 'This object is not protected.',
            '::display:object:flag:obfuscated' => 'This object is obfuscated.',
            '::display:object:flag:unobfuscated' => 'This object is not obfuscated.',
            '::display:object:flag:locked' => 'This entity is locked.',
            '::display:object:flag:unlocked' => 'This entity is unlocked.',
            '::display:object:flag:activated' => 'This object is activated.',
            '::display:object:flag:unactivated' => 'This object is not activated.',
            '::list:empty' => 'Empty list',
            '::yes' => 'Yes',
            '::no' => 'No',
            '::lock' => 'Locking',
            '::unlock' => 'Unlocking',
            '::entity:locked' => 'Entity locked. Unlock?',
            '::entity:unlocked' => 'Entity unlocked. Lock?',
            '::allApplications' => 'Bootstrap and applications',
            '::Version' => 'Version',
            '::version' => 'version',
            '::UniqueID' => 'Universal identifier : %s',
            '::progress' => 'In progress...',
            '::seeMore' => 'See more...',
            '::noContent' => '(content not available)',
            '::appSwitch' => 'Switch application',
            '::menu' => 'Menu',
            '::menuDesc' => 'Page with full menu',
            '::EmptyList' => 'Empty list.',
            '::ChangeLanguage' => 'Change language',
            '::SelectUser' => 'Select user',
            '::MarkAdd' => 'Mark',
            '::MarkRemove' => 'Unmark',
            '::MarkRemoveAll' => 'Unmark all',
            '::Synchronize' => 'Synchronize',
            '::notImplemented' => 'Not yet implemented...',
            '::notSupported' => 'Not supported...',
            '::password' => 'Password',
            '::login' => 'Connecting',
            '::confirm' => 'Confirm',
            '::privateKey' => 'Private key',
            '::connexion' => 'Connection',
            '::logout' => 'Disconnecting',
            '::selfLogout' => 'Disconnecting myself',
            '::flush' => 'Disconnecting all',
            '::return' => 'Return to application',
            '::previousPage' => 'Previous page',
            '::nextPage' => 'Next page',
            '::page%s%s%s%s%s' => 'Page %s/%s (%s-%s on %s)',
            '::limitedType' => 'Type of members is limited to "%s"',
            '::options' => 'Options',
            '::synchronize' => 'Synchronize',
            '::synchroAll' => 'Synchronize all',
            '::refreshList' => 'Refresh the list',

            // Groups
            '::group' => 'group',
            '::Group' => 'Group',
            '::closeGroup' => 'Closed group',
            '::openGroup' => 'Opened group',
            '::groups' => 'The groups',
            '::seeTheGroupNode' => 'See the group',
            '::seeTheGroupEntity' => 'See the group of entities',
            '::myGroupsNode' => 'My groups',
            '::myGroupsEntity' => 'My groups of entities',
            '::allGroupsNode' => 'All groups',
            '::allGroupsEntity' => 'All groups of entities',
            '::otherGroupsNode' => 'Groups of other entities',
            '::otherGroupsEntity' => 'Groups of other entities',
            '::createGroupNode' => 'Create a group',
            '::createGroupEntity' => 'Create a group of entities',
            '::createTheGroupNode' => 'Create the group',
            '::createTheGroupEntity' => 'Create the group',
            '::createGroupNodeOK' => 'The group have been created',
            '::createGroupEntityOK' => 'The group have been created',
            '::createGroupNodeNOK' => 'The group have not been created! %s',
            '::createGroupEntityNOK' => 'The group have not been created! %s',
            '::createClosedGroup' => 'Create a closed group',
            '::createObfuscatedGroup' => 'Create an obfuscated group',
            '::deleteGroup' => 'Delete the group',
            '::modifyGroupNode' => 'Modify the group',
            '::modifyGroupEntity' => 'Modify the group of entities',
            '::removeGroupNode' => 'Remove the group',
            '::removeGroupEntity' => 'Remove the group of entities',
            '::refuseGroupNode' => 'Refuse this object as group',
            '::refuseGroupEntity' => 'Refuse this object as group',
            '::getGroupNode' => 'Get a group',
            '::getGroupEntity' => 'Get a group of entities',
            '::returnToGroupNode' => 'Return to the group',
            '::returnToGroupEntity' => 'Return to the group',
            '::addMemberNode' => 'Add a member',
            '::addMemberEntity' => 'Add an entity as member',
            '::membersType' => 'Type of members',
            '::founder' => 'Founder',
            '::owner' => 'Owner',
            '::writer' => 'Writer',
            '::follower' => 'Follower',
            '::addAsOwner' => 'Add as owner',
            '::addAsWriter' => 'Add as writer',
            '::addAsFollower' => 'Add as follower',
            '::removeAsOwner' => 'Remove as owner',
            '::removeAsWriter' => 'Remove as writer',
            '::removeAsFollower' => 'Remove as follower',

            // Conversations
            '::conversation' => 'conversation',
            '::Conversation' => 'Conversation',
            '::closeConversation' => 'Closed conversation',
            '::openConversation' => 'Opened conversation',
            '::conversations' => 'The conversations',
            '::seeTheConversation' => 'See the conversation',
            '::myConversations' => 'My conversations',
            '::allConversations' => 'All conversations',
            '::otherConversations' => 'Conversations of other entities',
            '::createConversation' => 'Create a conversation',
            '::createTheConversation' => 'Create the conversation',
            '::createConversationOK' => 'The conversation have been created',
            '::createConversationNOK' => 'The conversation have not been created! %s',
            '::createClosedConversation' => 'Create a closed conversation',
            '::createObfuscatedConversation' => 'Create an obfuscated conversation',
            '::deleteConversation' => 'Delete the conversation',
            '::modifyConversation' => 'Modify the conversation',
            '::removeConversation' => 'Remove the conversation',
            '::refuseConversation' => 'Refuse this object as conversation',
            '::getConversation' => 'Get a conversation',
            '::returnToConversation' => 'Return to the conversation',

            // Folders
            '::folder' => 'folder',
            '::Folder' => 'Folder',
            '::closeFolder' => 'Closed folder',
            '::openFolder' => 'Opened folder',
            '::folders' => 'The folders',
            '::seeTheFolder' => 'See the folder',
            '::myFolders' => 'My folders',
            '::allFolders' => 'All folders',
            '::otherFolders' => 'Folders of other entities',
            '::createFolder' => 'Create a folder',
            '::createTheFolder' => 'Create the folder',
            '::createFolderOK' => 'The folder have been created',
            '::createFolderNOK' => 'The folder have not been created! %s',
            '::createClosedFolder' => 'Create a closed folder',
            '::createObfuscatedFolder' => 'Create an obfuscated folder',
            '::deleteFolder' => 'Delete the folder',
            '::modifyFolder' => 'Modify the folder',
            '::removeFolder' => 'Remove the folder',
            '::refuseFolder' => 'Refuse this object as folder',
            '::getFolder' => 'Get a folder',
            '::returnToFolder' => 'Return to the folder',

            // Galleries
            '::gallery' => 'gallery',
            '::Gallery' => 'Gallery',
            '::closeGallery' => 'Closed gallery',
            '::openGallery' => 'Opened gallery',
            '::galleries' => 'The galleries',
            '::seeTheGallery' => 'See the gallery',
            '::myGalleries' => 'My galleries',
            '::allGalleries' => 'All galleries',
            '::otherGalleries' => 'Galleries of other entities',
            '::createGallery' => 'Create a gallery',
            '::createTheGallery' => 'Create the gallery',
            '::createGalleryOK' => 'The gallery have been created',
            '::createGalleryNOK' => 'The gallery have not been created! %s',
            '::createClosedGallery' => 'Create a closed gallery',
            '::createObfuscatedGallery' => 'Create an obfuscated gallery',
            '::deleteGallery' => 'Delete the gallery',
            '::modifyGallery' => 'Modify the gallery',
            '::removeGallery' => 'Remove the gallery',
            '::refuseGallery' => 'Refuse this object as gallery',
            '::getGallery' => 'Get a gallery',
            '::returnToGallery' => 'Return to the gallery',

            // Blogs
            '::blog' => 'blog',
            '::Blog' => 'Blog',
            '::closeBlog' => 'Closed blog',
            '::openBlog' => 'Opened blog',
            '::blogs' => 'The blogs',
            '::seeTheBlog' => 'See the blog',
            '::myBlogs' => 'My blogs',
            '::allBlogs' => 'All blogs',
            '::otherBlogs' => 'Blogs of other entities',
            '::createBlog' => 'Create a blog',
            '::createTheBlog' => 'Create the blog',
            '::createBlogOK' => 'The blog have been created',
            '::createBlogNOK' => 'The blog have not been created! %s',
            '::createClosedBlog' => 'Create a closed blog',
            '::createObfuscatedBlog' => 'Create an obfuscated blog',
            '::deleteBlog' => 'Delete the blog',
            '::modifyBlog' => 'Modify the blog',
            '::removeBlog' => 'Remove the blog',
            '::refuseBlog' => 'Refuse this object as blog',
            '::getBlog' => 'Get a blog',
            '::returnToBlog' => 'Return to the blog',
        ],
        'en-en' => [
            '::translateModule:de-de:ModuleName' => 'German (Germany)',
            '::translateModule:de-de:MenuName' => 'German (Germany)',
            '::translateModule:de-de:ModuleDescription' => 'Interface translation in German.',
            '::translateModule:de-de:ModuleHelp' => 'This module permit to translate the nebule applications in German.',
        ],
    ];
}
